server:
  port: 80
  servlet:
    context-path: /Shopme
spring:
  datasource:
    password: divine96
    url: jdbc:mysql://localhost:3316/shopmebd
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: false
  mail:
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
             client-id: 39403343429-ljpn095m5udrdi5h61tspauq89p7mpoq.apps.googleusercontent.com
             client-secret: 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
             scope:
             - email
             - profile
          facebook:
             client-id: 1076518902954736
             client-secret: fd828aa2d156e46bd4dbc838e2d79b06
             scope:
             - email
             - public_profile